-- English Jokes
INSERT INTO jokes (joke, language) VALUES ('Why don’t skeletons fight each other? They don’t have the guts!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call fake spaghetti? An impasta!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the scarecrow win an award? Because he was outstanding in his field!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What has keys but can’t open locks? A keyboard!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why don’t eggs tell jokes? They’d crack each other up!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call cheese that isn’t yours? Nacho cheese!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the math book look so sad? It had too many problems!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a bear with no teeth? A gummy bear!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why don’t scientists trust atoms? Because they make up everything!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish wearing a bowtie? Sofishticated!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the golfer bring two pairs of pants? In case he got a hole in one!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a sleeping bull? A bulldozer!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the scarecrow get promoted? Because he was outstanding in his field!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a dinosaur with an extensive vocabulary? A thesaurus!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the bicycle fall over? Because it was two-tired!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pile of cats? A meow-ntain!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the tomato turn red? Because it saw the salad dressing!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow with no legs? Ground beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why don’t oysters donate to charity? Because they’re shellfish!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a bee that tells jokes? A humdinger!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his money in the freezer? He wanted cold hard cash!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a lazy kangaroo? A pouch potato!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the computer go to the doctor? It had a virus!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish with no eyes? Fsh!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the teacher wear sunglasses? Because her students were so bright!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a duck that gets straight As? A wise quacker!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why don’t skeletons fight each other? They don’t have the guts!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a dog magician? A labracadabrador!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man use ketchup in the shower? Because it was raining catsup and dogs!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that does karate? A pork chop!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the oven? He wanted a hot ride!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a sheep covered in chocolate? A candy baa!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the banana go to the zoo? Because it wanted to hang out with the monkey!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish that wears a crown? King mackerel!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the coffee file a police report? It got mugged!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that just gave birth? De-calfinated!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man use catsup in the shower? Because he wanted to wash away his sins!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a chicken that crosses the road, rolls in mud, and crosses the road again? Dirty double-crosser!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man throw butter out the window? To see the butter-fly!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that plays an instrument? A moo-sician!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his money in the blender? He wanted liquid assets!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a group of unorganized cats? A cat-astrophe!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man sit on the sideline at the game? He didn’t want to take sides!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish that tells jokes? A clownfish!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in reverse? He wanted to back out of trouble!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a deer with no eyes? No idea!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man go broke buying watches? He lost track of time!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a dog that tells time? A watch dog!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his radio in the fridge? He wanted cool music!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a snowman party? A snowball!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his bed in the fireplace? He wanted to sleep like a log!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a horse that lives next door? A neigh-bor!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the microwave? He wanted to see what a hot call looked like!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always on time? Punctual pork!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his spoon in the freezer? He wanted cold soup!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that jumps over a barbed wire fence? Beef jerky!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his wallet under his pillow? He wanted to dream about money!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a sheep that tells jokes? A baa-d comedian!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his pencil in the oven? He wanted to draw some heat!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a bird that tells jokes? A tweet!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his clock in the oven? He wanted to see what time it was cooked!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow with a twitch? Beef jerky!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his glasses in the freezer? He wanted cool vision!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish with no eyes and no nose? Fsh and fsh!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the microwave? He wanted a hot rod!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always late? Tardy beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the blender? He wanted a smooth call!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that loves math? A pork-ulator!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his TV in the fridge? He wanted cool shows!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish that wears a hat? A salmon-chanted evening!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his chair in the oven? He wanted a hot seat!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a dog that likes to bowl? A strike hound!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his desk in the shower? He wanted wet work!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow with a sunburn? Well-done beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his lamp in the freezer? He wanted cool light!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that tells jokes? A ham-orous!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his shoes in the fridge? He wanted cold feet!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that tells jokes? A moo-dy comedian!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the oven? He wanted a hotline!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish with a great sense of humor? A clownfish!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his computer in the shower? He wanted to surf the net!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s good at basketball? A slam-ham!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his socks in the fridge? He wanted cold feet!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always happy? Moo-dy!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his bed in the oven? He wanted a warm bed!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always on time? Punctual pork!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the microwave? He wanted to talk turkey!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a fish that’s always late? Tardy trout!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his wallet in the oven? He wanted hot cash!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always running? Fast food!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the shower? He wanted a clean getaway!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always angry? Boar-ed!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the freezer? He wanted icy calls!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always tired? Sleepy beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his bed in the microwave? He wanted a quick nap!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always sleepy? Nap-pork!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the fridge? He wanted cool conversations!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always singing? Moo-sical!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the fridge? He wanted a chill ride!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always dancing? Boogie pork!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his wallet in the shower? He wanted wet money!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always laughing? Moo-dicrous!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his bed in the freezer? He wanted a frozen mattress!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always crying? Sow-rry!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the oven? He wanted a hot connection!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always working? Busy beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the microwave? He wanted a fast ride!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always eating? Chow-pork!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his wallet in the microwave? He wanted to heat up his money!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always reading? Bookish beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his phone in the shower? He wanted steamy calls!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a pig that’s always studying? Pork-ademic!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his bed in the fridge? He wanted a cold bed!', 'en');
INSERT INTO jokes (joke, language) VALUES ('What do you call a cow that’s always traveling? Roaming beef!', 'en');
INSERT INTO jokes (joke, language) VALUES ('Why did the man put his car in the freezer? He wanted an ice ride!', 'en');